services:
  jorani:
    build: .
    ports:
      - "80:80"
    env_file: .env
    depends_on:
      - mysql
  mysql:
    image: mysql:8
    ports:
      - "3306:3306"
    env_file: .env
    volumes:
      - ./legacy/sql/init:/docker-entrypoint-initdb.d
