services:
  jorani:
    env_file: .env
    volumes:
      - .:/var/www/html
    depends_on:
      - composer
  composer:
    image: composer:latest
    volumes:
      - .:/app
    command: install --working-dir=/app/legacy --ignore-platform-reqs
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "8025:8025"
      - "${SMTP_PORT}:${SMTP_PORT}"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: "1"
      MP_SMTP_AUTH_ALLOW_INSECURE: "1"
  ldap:
    image: public.ecr.aws/bitnami/openldap:latest
    environment:
      LDAP_ROOT: "${LDAP_BASEDN}"
      LDAP_ADMIN_USERNAME: "admin"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CUSTOM_LDIF_DIR: "/ldifs"
    ports:
      - "${LDAP_PORT}:1389"
    volumes:
      - ldap_data:/bitnami/openldap
      - ./docker/ldap/ldif:/ldifs:ro
  saml-idp:
    image: kenchan0130/simplesamlphp
    container_name: saml-idp
    ports:
      - "8080:8080"
    environment:
      SIMPLESAMLPHP_SP_ENTITY_ID: "http://localhost/api/metadata"
      SIMPLESAMLPHP_SP_ASSERTION_CONSUMER_SERVICE: "http://localhost/api/acs"
      SIMPLESAMLPHP_SP_SINGLE_LOGOUT_SERVICE: "http://localhost/api/sls"
    volumes:
      - ./docker/simplesamlphp/config/authsources.php:/var/www/simplesamlphp/config/authsources.php
      - ./docker/simplesamlphp/config/config.php:/var/www/simplesamlphp/config/config.php
      - ./docker/simplesamlphp/metadata/saml20-idp-hosted.php:/var/www/simplesamlphp/metadata/saml20-idp-hosted.php
      - ./docker/simplesamlphp/cert/my-idp.crt:/var/www/simplesamlphp/cert/my-idp.crt:ro
      - ./docker/simplesamlphp/cert/my-idp.pem:/var/www/simplesamlphp/cert/my-idp.pem:ro
volumes:
  ldap_data:
