<?php
// psalm-stubs.php

/**
 * Fake file (Stub) to help Psalm understand CodeIgniter 3's database magic.
 * NEVER include this file in your production code.
 */
class CI_DB extends CI_DB_query_builder
{
    /**
     * Returns the ID generated by the last INSERT query
     * @return int|string
     */
    public function insert_id()
    {
    }

    /**
     * Returns the number of rows affected by the last write query
     * @return int
     */
    public function affected_rows()
    {
    }

    /**
     * Returns the last database error
     * @return array{code: int, message: string}
     */
    public function error()
    {
    }

    // Add other missing $this->db methods here if Psalm finds any!
}
